name: ShellCheck

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "shellcheck"
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: shellcheck mac
